#!/usr/bin/env bash
# Цифровая интенсивность (digital vibrance), как в панели NVIDIA на Windows.
#
#   vibrance.sh set <0..100>   — выставить и применить
#   vibrance.sh get            — текущее значение
#   vibrance.sh restore        — применить сохранённое (для автозапуска)
#
# На Wayland ручки из nvidia-settings нет: та работала через XRandR и на
# сеансе Wayland не действует вовсе. Зато цветом всего экрана распоряжается
# сам компоновщик — Hyprland умеет прогонять кадр через свой шейдер, и
# насыщенность считается там же, где картинка собирается. Способ не зависит
# от видеокарты: одинаково работает на NVIDIA, AMD и Intel.
#
# Шкала намеренно повторяет привычную: 50 — как есть, 100 — максимум,
# ниже 50 — приглушение до чёрно-белого на нуле.
set -u

CONF="${XDG_CONFIG_HOME:-$HOME/.config}"
SHADER_DIR="$CONF/hypr/shaders"
SHADER="$SHADER_DIR/vibrance.frag"
STATE="$CONF/panacea/.vibrance"

cur() { [ -f "$STATE" ] && cat "$STATE" || echo 50; }

# Сказать Hyprland, какой шейдер брать.
#
# Через hyprctl eval, а не keyword: новый (не-legacy, он же Lua) парсер
# конфига keyword молча отвергает — и выходит при этом с нулевым кодом, так
# что ошибку не видно, а настройка никуда не уезжает. Ровно то же самое уже
# случилось с настройками мониторов. keyword оставляем запасным путём для
# старых конфигов.
set_shader() {
    local val="$1" out
    out="$(hyprctl eval "hl.config({ decoration = { screen_shader = \"$val\" } })" 2>&1)"
    case "$out" in
        ok*) return 0 ;;
        *)   hyprctl keyword decoration:screen_shader "$val" >/dev/null 2>&1 ;;
    esac
}

apply() {
    local pct="$1"

    # 50 — нейтраль: шейдер снимаем совсем, чтобы кадр шёл мимо лишнего
    # прохода. Так «выключено» действительно ничего не стоит.
    if [ "$pct" -eq 50 ]; then
        set_shader '[[EMPTY]]'
        return
    fi

    # 50→0.0, 100→1.0, 0→-1.0
    local strength
    strength="$(awk -v p="$pct" 'BEGIN { printf "%.4f", (p - 50) / 50 }')"

    mkdir -p "$SHADER_DIR"
    # GLSL ES 1.00 (varying/texture2D/gl_FragColor), без строки #version.
    # Именно этот диалект Hyprland подставляет в свой конвейер: на «#version
    # 300 es» драйвер NVIDIA отвечает «error C3001: no program defined» и
    # рисует поверх экрана красную рамку с ошибкой вместо картинки.
    # Только ASCII: компилятор NVIDIA спотыкается на не-ASCII байтах даже
    # внутри комментариев и отвечает «error C3001: no program defined», то
    # есть будто исходника нет вовсе. Поэтому пояснения по-русски остаются
    # здесь, в скрипте, а в сам .frag уходит английский.
    #
    # lum  — яркость по Rec.709, серый той же светлоты, что и цвет: от него
    #        отталкиваемся, чтобы подъём насыщенности не гнал в пересвет.
    # sat  — насколько цвет насыщен сейчас. В этом и отличие «вибранса» от
    #        простой насыщенности: уже яркие цвета трогаем слабо, блёклые —
    #        сильно, иначе лица и небо первыми уезжают в кислоту.
    #
    # Пишем во временный файл и переименовываем. Компоновщик перечитывает
    # шейдер, как только ему называют путь, а ползунок зовёт нас на каждое
    # движение — и Hyprland успевал открыть файл на середине записи. Пустой
    # или обрезанный исходник он и показывает красной рамкой «error C3001».
    # Переименование в пределах файловой системы атомарно: компоновщик видит
    # либо старый файл целиком, либо новый целиком.
    tmp="$SHADER.new"
    cat > "$tmp" <<EOF
// Generated by panacea/scripts/vibrance.sh -- edits will be overwritten.
precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;

const float STRENGTH = ${strength};

void main() {
    vec4 px = texture2D(tex, v_texcoord);

    float lum = dot(px.rgb, vec3(0.2126, 0.7152, 0.0722));

    float mx  = max(px.r, max(px.g, px.b));
    float mn  = min(px.r, min(px.g, px.b));
    float sat = mx - mn;

    float weight = STRENGTH > 0.0 ? (1.0 - sat) : 1.0;
    float amount = STRENGTH * weight;
    vec3 outRgb = mix(vec3(lum), px.rgb, 1.0 + amount);

    gl_FragColor = vec4(clamp(outRgb, 0.0, 1.0), px.a);
}
EOF
    mv -f "$tmp" "$SHADER"

    set_shader "$SHADER"
}

case "${1:-}" in
    set)
        pct="${2:-50}"
        [ "$pct" -lt 0 ]   && pct=0
        [ "$pct" -gt 100 ] && pct=100
        mkdir -p "$(dirname "$STATE")"
        echo "$pct" > "$STATE"
        apply "$pct"
        echo "$pct"
        ;;
    get)     cur ;;
    restore) apply "$(cur)" ;;
    *)       echo "usage: vibrance.sh set <0..100>|get|restore" >&2; exit 1 ;;
esac
