-- Custom Autostart Programs & Daemons (Lua)
--
-- API: hl.exec_cmd(command) inside the "hyprland.start" event
--
-- Examples:
-- hl.on("hyprland.start", function()
--     hl.exec_cmd("discord --start-minimized")
--     hl.exec_cmd("telegram-desktop -autostart")
-- end)
