# ==============================================================================
# Custom Autostart Programs & Daemons (Пользовательский автозапуск)
# ==============================================================================
# Examples:
# exec-once = discord --start-minimized
# exec-once = telegram-desktop -autostart
# exec-once = steam -silent
