-- Custom General Settings & Overrides (Lua)
--
-- API: hl.config({ section = { key = value } })
--
-- Examples:
-- hl.config({ general = { gaps_in = 6, gaps_out = 12 } })
-- hl.config({ decoration = { rounding = 12 } })
