# ==============================================================================
# Custom Window Rules & Layer Rules (Пользовательские правила окон)
# ==============================================================================
# Examples:
# windowrulev2 = float, class:^(mpv)$
# windowrulev2 = size 1000 600, class:^(mpv)$
# windowrulev2 = workspace 3, class:^(discord)$
# windowrulev2 = opacity 0.90 0.90, class:^(Spotify)$
