# ==============================================================================
# Custom User Configuration Fallback (Дополнительный конфиг)
# ==============================================================================
# You can place any additional Hyprland directives or source external files here.
