-- Custom Window Rules & Layer Rules (Lua)
--
-- API: hl.window_rule({ name = ..., match = { ... }, <rule> = ... })
--
-- Examples:
-- hl.window_rule({ name = "mpv-float", match = { class = "^(mpv)$" }, float = true })
-- hl.window_rule({ name = "discord-ws3", match = { class = "^(discord)$" }, workspace = "3" })
